### ISSUE TITLE
Feedback on Reactive Messaging Acknowledgement guide conversion to SNL

### ISSUE THREAD

**Issue by GraceJansen** [OpenLiberty/quick-labs#51]
- [x] Architecture diagram missing on first page —> remove reference to diagram as we will not be including it

- [x] Additional pre-reqs page not needed now

- [x] Missing this sentence —> The finish directory contains the finished project that you will build.

- [x] Not sure why this is there —> start/SystemService.java in the Choosing an acknowledgment strategy section?

- [x] POSTPROCESSING —> style is incorrect, should be underscore and in box type

- [x] Not sure why this section is all in italics, not needed —> strategy by default. If the acknowledgment strategy is set to

- [x] This formatting has gone funny - should just be bullet points ins the text not in a code box —> - If the method emits data, the incoming message is acknowledged after the outgoing message is acknowledged. - If the method doesn't emit data, the incoming message is acknowledged after the method or processing completes.

- [x] All this text is formatted incorrectly, should be normal text —> “ Its important that the methods use the **POST_PROCESSING** strategy because it fulfills the requirement that a message isn't acknowledged until after the message is fully processed. This processing strategy is beneficial in situations where messages must reliably not get lost. When the **POST_PROCESSING** acknowledgment strategy cant be “  

————
Implementing the MANUAL acknowledgment strategy
———
- [x] This shouldn’t be here —> finish/SystemService.java

- [x]  This should just be normal text as bullet points —> - If the system property **isn't valid**, the method **acknowledges**
    the incoming message and **returns** an empty reactive stream. The processing is
    complete. - If the system property is valid, the method creates a **message** with the value of the
    requested system property and sends it to the proper channel. The method acknowledges the incoming message only
    after the sent message is acknowledged.

———
Waiting for a message to be acknowledged
———
- [x] This shouldn’t be here —> InventoryResource.java

- [x] Missing semicolon at the end of the provided replacement for InventoryResource.java file

——
Building and running the application
———
- [x] Command not formatted correctly to be copyable. Should be two separate commands—> docker build -t system:1.0-SNAPSHOT system/. docker build -t inventory:1.0-SNAPSHOT inventory/.

- [x] Issues with formatting at the bottom of this page —> weird -- unnecessary lines here and command not formatted correctly to be copyable again - ./scripts/startContainers.sh

——
Testing the application
———
- [x] Missing this sentence —> Go to the http://localhost:9085/inventory/systems URL to access the inventory microservice. You see the CPU systemLoad property for all the systems: (Only have “Go to the” at the moment)

- [x] Need to remove comments or format them correctly for SNL —> otherwise curl commands will result in error 500

- [x] Curl command not formatted correctly for copying —> curl -X PUT -d "os.name" http://localhost:9085/inventory/data --header "Content-Type:text/plain"

——
Tearing down the environment
——
- [x] Command not configured correctly for copying —> ./scripts/stopContainers.sh

- [x] The command —> rmdir guide-microprofile-reactive-messaging-acknowledgment -  Fails to remove the directory

**Comment by jamiecoleman92** [comment]
All issues expect the final one as that is an environmental issue should now be fixed. @GraceJansen please confirm when you have made your review.

**Comment by GraceJansen** [comment]
- [ ] POSTPROCESSING and PREPROCESSING are still not formatted correctly (I've attached what they should look like from the OpenLiberty guide website and what they look like in SNL atm for reference).
<img width="535" alt="Screenshot 2020-09-16 at 11 19 36" src="https://user-images.githubusercontent.com/32962135/93325052-9ddda280-f80e-11ea-85a3-dd9bc52303ae.png">

<img width="458" alt="Screenshot 2020-09-16 at 11 19 50" src="https://user-images.githubusercontent.com/32962135/93325045-9cac7580-f80e-11ea-9fd0-7855133b9fa7.png">


- [ ] The above issue has led to much of the text being italicized for no reason. Please could unnecessary italics from the _Choosing an acknowledgment strategy_ section be removed.

**Comment by jakub-pomykala** [comment]
Done
